"""add module members and invite tokens

Revision ID: d438927961fb
Revises: b6977f759fde
Create Date: 2026-09-30 17:27:19.970312

"""
import secrets
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd438927961fb'
down_revision: Union[str, Sequence[str], None] = 'b6977f759fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_id', name='uq_module_members_user_module')
    )
    op.create_index(op.f('ix_module_members_module_id'), 'module_members', ['module_id'], unique=False)
    op.create_index(op.f('ix_module_members_user_id'), 'module_members', ['user_id'], unique=False)
    op.add_column('modules', sa.Column('invite_token', sa.String(length=43), nullable=True))
    # ### end Alembic commands ###
    backfill_invite_tokens()
    op.alter_column('modules', 'invite_token',
               existing_type=sa.String(length=43),
               nullable=False)
    op.create_index(op.f('ix_modules_invite_token'), 'modules', ['invite_token'], unique=True)


def backfill_invite_tokens() -> None:
    connection = op.get_bind()
    module_ids = connection.execute(sa.text('SELECT id FROM modules')).scalars().all()
    for module_id in module_ids:
        connection.execute(
            sa.text(
                'UPDATE modules SET invite_token = :token WHERE id = :module_id'
            ),
            {'token': secrets.token_urlsafe(32), 'module_id': module_id},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modules_invite_token'), table_name='modules')
    op.drop_column('modules', 'invite_token')
    op.drop_index(op.f('ix_module_members_user_id'), table_name='module_members')
    op.drop_index(op.f('ix_module_members_module_id'), table_name='module_members')
    op.drop_table('module_members')
    # ### end Alembic commands ###
