"""create modules table and link files

Revision ID: f9203759bdbb
Revises: ed7edfc02cc2
Create Date: 2026-09-26 12:42:15.332795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9203759bdbb'
down_revision: Union[str, Sequence[str], None] = 'ed7edfc02cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_user_id'), 'modules', ['user_id'], unique=False)
    op.create_foreign_key('fk_files_module_id_modules', 'files', 'modules', ['module_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_files_module_id_modules', 'files', type_='foreignkey')
    op.drop_index(op.f('ix_modules_user_id'), table_name='modules')
    op.drop_table('modules')
    # ### end Alembic commands ###
